apiVersion: v1
kind: Secret
metadata:
  name: daytrader-minio-backup
  namespace: saxo
type: Opaque
stringData:
  ACCESS_KEY_ID: "__MINIO_ROOT_USER__"
  ACCESS_SECRET_KEY: "__MINIO_ROOT_PASSWORD__"
---
apiVersion: v1
kind: Secret
metadata:
  name: daytrader-postgres-app
  namespace: saxo
type: kubernetes.io/basic-auth
stringData:
  username: "__POSTGRES_APP_USER__"
  password: "__POSTGRES_APP_PASSWORD__"
  database-url: "__DATABASE_URL__"
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: daytrader-postgres
  namespace: saxo
spec:
  instances: 2
  bootstrap:
    initdb:
      database: daytrader
      owner: __POSTGRES_APP_USER__
      secret:
        name: daytrader-postgres-app
  storage:
    size: 5Gi
  backup:
    retentionPolicy: "3650d"
    barmanObjectStore:
      destinationPath: s3://daytrader-cnpg/
      endpointURL: __MINIO_ENDPOINT_URL__
      s3Credentials:
        accessKeyId:
          name: daytrader-minio-backup
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: daytrader-minio-backup
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
