from __future__ import annotations

import json
import sys
import uuid
from datetime import UTC, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from saxo_daytrader_xai import notifications
from saxo_daytrader_xai.config import load_config
from saxo_daytrader_xai.db import connect, init_db
from saxo_daytrader_xai.execution_engine import queue_and_maybe_execute_latest_report
from saxo_daytrader_xai.importer import sync_portfolio
from saxo_daytrader_xai.notifications import fetch_notification_deliveries


class _FakeSlackResponse:
    status_code = 200

    def raise_for_status(self) -> None:
        return None


def _insert_completed_report(connection) -> int:
    created_at = datetime.now(UTC).isoformat(timespec="seconds")
    report_json = {
        "report_title": "Phase 35 Validation Decision Report",
        "analysis_window_active": True,
        "goal": "Validation run",
        "market_regime": {"summary": "Synthetic validation context"},
        "portfolio_assessment": {"summary": "Queue processor notification coverage"},
        "reasoning_steps": ["Queue orders", "Dispatch success, warning, and failure alerts"],
        "risk_rules_check": ["Validation only"],
        "watchlist_focus": [],
        "suggested_trades": [],
        "execution_notes": ["Generated by scripts/validate_phase35.py"],
        "daily_target_assessment": "Validation only.",
    }
    cursor = connection.execute(
        """
        INSERT INTO decision_reports (
            created_at, report_date, batch_id, model, status, analysis_window_active,
            response_id, prompt_text, request_json, response_json, report_json, error_text
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            created_at,
            created_at[:10],
            "phase35-validation",
            "mock-validator",
            "completed",
            1,
            "phase35-validation",
            json.dumps({"source": "validate_phase35"}, ensure_ascii=False, sort_keys=True),
            json.dumps({"source": "validate_phase35"}, ensure_ascii=False, sort_keys=True),
            json.dumps({"source": "validate_phase35"}, ensure_ascii=False, sort_keys=True),
            json.dumps(report_json, ensure_ascii=False, sort_keys=True),
            None,
        ),
    )
    connection.commit()
    return int(cursor.lastrowid)


def _insert_execution_order(
    connection,
    *,
    report_id: int,
    symbol: str,
    action: str,
    status: str,
    quantity: float,
    price_local: float,
    estimated_value_dkk: float,
    error_text: str | None = None,
) -> int:
    cursor = connection.execute(
        """
        INSERT INTO execution_orders (
            created_at, report_id, symbol, action, mode, status, adapter,
            requested_weight_pct, quantity, price_local, currency, estimated_value_dkk,
            approval_required, approved_at, ledger_id, broker_order_id, request_json, execution_result_json, error_text
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            datetime.now(UTC).isoformat(timespec="seconds"),
            report_id,
            symbol,
            action,
            "simulation",
            status,
            "saxo",
            0.03,
            quantity,
            price_local,
            "USD",
            estimated_value_dkk,
            0,
            datetime.now(UTC).isoformat(timespec="seconds") if status == "executed" else None,
            None,
            None,
            json.dumps({"source": "validate_phase35"}, ensure_ascii=False, sort_keys=True),
            json.dumps({"status": status}, ensure_ascii=False, sort_keys=True),
            error_text,
        ),
    )
    connection.commit()
    return int(cursor.lastrowid)


def main() -> int:
    config = load_config(ROOT / "config.yaml")
    db_path = Path("/tmp") / f"saxo_daytrader_phase35_{uuid.uuid4().hex}.db"
    config["portfolio"]["database_path"] = str(db_path)
    config["notifications"]["slack"]["enabled"] = True
    config["notifications"]["slack"]["webhook_url"] = "https://hooks.slack.test/services/T000/B000/XXX"
    config["notifications"]["email"]["enabled"] = False
    config["notifications"]["alerts"]["execution_success_enabled"] = True
    config["notifications"]["alerts"]["execution_warning_enabled"] = True
    config["notifications"]["alerts"]["execution_failure_enabled"] = True
    config["notifications"]["alerts"]["broker_fill_enabled"] = False
    config["notifications"]["alerts"]["broker_reject_enabled"] = False
    config["notifications"]["alerts"]["broker_cancel_enabled"] = False
    config["notifications"]["alerts"]["broker_management_failure_enabled"] = False

    result = sync_portfolio(config)
    connection = connect(config["portfolio"]["database_path"])
    init_db(connection)

    report_id = _insert_completed_report(connection)
    _insert_execution_order(
        connection,
        report_id=report_id,
        symbol="MSTR:xnas",
        action="SELL",
        status="executed",
        quantity=11.0,
        price_local=126.98,
        estimated_value_dkk=9440.0,
    )
    _insert_execution_order(
        connection,
        report_id=report_id,
        symbol="SBUX:xnas",
        action="BUY",
        status="pending_approval",
        quantity=12.0,
        price_local=93.65,
        estimated_value_dkk=7286.12,
    )
    _insert_execution_order(
        connection,
        report_id=report_id,
        symbol="FIGR:xnas",
        action="SELL",
        status="execution_failed",
        quantity=50.0,
        price_local=32.25,
        estimated_value_dkk=10226.42,
        error_text="No tradable Saxo instrument match found for FIGR:xnas",
    )

    slack_calls: list[dict] = []
    original_post = notifications.requests.post

    def fake_post(url: str, **kwargs):
        slack_calls.append({"url": url, "json": kwargs.get("json")})
        return _FakeSlackResponse()

    notifications.requests.post = fake_post
    try:
        queue_result = queue_and_maybe_execute_latest_report(config=config, connection=connection)
        second_queue_result = queue_and_maybe_execute_latest_report(config=config, connection=connection)
    finally:
        notifications.requests.post = original_post

    deliveries = fetch_notification_deliveries(connection, limit=20)
    sent_rows = [row for row in deliveries if row["status"] == "sent"]
    summary_kinds = {row["summary_kind"] for row in sent_rows}

    assert queue_result["status"] == "ok", queue_result
    assert queue_result["alerts"]["status"] == "ok", queue_result["alerts"]
    assert second_queue_result["status"] == "ok", second_queue_result
    assert "alert_execution_success" in summary_kinds, summary_kinds
    assert "alert_execution_warning" in summary_kinds, summary_kinds
    assert "alert_execution_failed" in summary_kinds, summary_kinds
    assert len(sent_rows) == 3, sent_rows
    assert len(slack_calls) == 3, slack_calls
    assert all(row["status"] in {"sent", "skipped"} for row in second_queue_result["alerts"]["sent"]), second_queue_result["alerts"]
    assert any(row["status"] == "skipped" for row in second_queue_result["alerts"]["sent"]), second_queue_result["alerts"]

    print("Phase 35 validation passed.")
    print(f"Imported source positions: {result.source_positions}")
    print(f"Excluded positions: {result.excluded_positions}")
    print(f"Alert deliveries sent: {len(sent_rows)}")
    print(f"Summary kinds sent: {', '.join(sorted(summary_kinds))}")
    print(f"Slack success payloads: {len(slack_calls)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
