from __future__ import annotations

import json
import sys
import uuid
from datetime import UTC, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from saxo_daytrader_xai.config import load_config
from saxo_daytrader_xai.db import connect, init_db
from saxo_daytrader_xai.execution_engine import (
    execute_order,
    export_audit_bundle,
    fetch_execution_orders,
    queue_and_maybe_execute_latest_report,
)
from saxo_daytrader_xai.importer import sync_portfolio
from saxo_daytrader_xai.portfolio import fetch_portfolio_positions
from saxo_daytrader_xai.scheduler_service import run_scheduler_cycle


def _insert_completed_report(connection, suggestions: list[dict[str, object]]) -> int:
    created_at = datetime.now(UTC).isoformat(timespec="seconds")
    report_json = {
        "report_title": "Phase 5 Validation Decision Report",
        "analysis_window_active": True,
        "goal": "Validation run",
        "market_regime": {"summary": "Synthetic validation context"},
        "portfolio_assessment": {"summary": "Synthetic report for queue/execution tests"},
        "reasoning_steps": ["Validate queue creation", "Validate simulation execution"],
        "risk_rules_check": ["Excluded symbols remain blocked", "No shorting allowed"],
        "watchlist_focus": [],
        "suggested_trades": suggestions,
        "execution_notes": ["Generated by scripts/validate_phase5.py"],
        "daily_target_assessment": "Validation only.",
    }
    cursor = connection.execute(
        """
        INSERT INTO decision_reports (
            created_at, report_date, batch_id, model, status, analysis_window_active,
            response_id, prompt_text, request_json, response_json, report_json, error_text
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            created_at,
            created_at[:10],
            "phase5-validation",
            "mock-validator",
            "completed",
            1,
            "phase5-validation",
            json.dumps({"source": "validate_phase5"}, ensure_ascii=False, sort_keys=True),
            json.dumps({"source": "validate_phase5"}, ensure_ascii=False, sort_keys=True),
            json.dumps({"source": "validate_phase5"}, ensure_ascii=False, sort_keys=True),
            json.dumps(report_json, ensure_ascii=False, sort_keys=True),
            None,
        ),
    )
    connection.commit()
    return int(cursor.lastrowid)


def _insert_manual_order(
    connection,
    *,
    symbol: str,
    action: str,
    mode: str,
    quantity: float,
    price_local: float,
    currency: str,
    estimated_value_dkk: float,
) -> int:
    cursor = connection.execute(
        """
        INSERT INTO execution_orders (
            created_at, report_id, symbol, action, mode, status, adapter,
            requested_weight_pct, quantity, price_local, currency, estimated_value_dkk,
            approval_required, request_json, execution_result_json, error_text
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            datetime.now(UTC).isoformat(timespec="seconds"),
            None,
            symbol,
            action,
            mode,
            "pending_execution",
            "saxo",
            None,
            quantity,
            price_local,
            currency,
            estimated_value_dkk,
            0,
            json.dumps({"source": "validate_phase5_manual"}, ensure_ascii=False, sort_keys=True),
            None,
            None,
        ),
    )
    connection.commit()
    return int(cursor.lastrowid)


def main() -> int:
    config = load_config(ROOT / "config.yaml")
    db_path = Path("/tmp") / f"saxo_daytrader_phase5_{uuid.uuid4().hex}.db"
    export_dir = Path("/tmp") / f"saxo_daytrader_phase5_export_{uuid.uuid4().hex}"
    config["portfolio"]["database_path"] = str(db_path)
    config["execution"]["mode"] = "simulation"
    config["execution"]["auto_execute_simulation"] = True
    config["execution"]["max_daily_orders"] = 4
    config["app"]["dry_run"] = True

    result = sync_portfolio(config)
    connection = connect(config["portfolio"]["database_path"])
    init_db(connection)

    positions = fetch_portfolio_positions(connection)
    assert len(positions) >= 2, "Expected at least two imported positions"

    sell_position = next(
        (row for row in positions if row["current_price_local"] not in (None, 0) and float(row["allocation_pct"]) > 0.02),
        positions[0],
    )
    buy_position = next(
        (row for row in reversed(positions) if row["current_price_local"] not in (None, 0) and row["symbol"] != sell_position["symbol"]),
        positions[-1],
    )
    sell_target = max(float(sell_position["allocation_pct"]) - 0.02, 0.01)
    buy_target = min(float(buy_position["allocation_pct"]) + 0.03, float(config["risk"]["max_position_weight"]))

    report_id = _insert_completed_report(
        connection,
        [
            {
                "action": "SELL",
                "symbol": sell_position["symbol"],
                "target_weight_pct": round(sell_target, 6),
                "quantity_hint": "Trim position by target weight",
                "confidence": 0.7,
                "priority": "medium",
                "rationale": "Validation sell path",
                "risk_notes": ["Validation only"],
            },
            {
                "action": "BUY",
                "symbol": buy_position["symbol"],
                "target_weight_pct": round(buy_target, 6),
                "quantity_hint": "Increase smaller position",
                "confidence": 0.72,
                "priority": "medium",
                "rationale": "Validation buy path",
                "risk_notes": ["Validation only"],
            },
        ],
    )

    queue_result = queue_and_maybe_execute_latest_report(config=config, connection=connection)
    queued_orders = queue_result.get("orders", [])
    sell_estimate = float(sell_position["market_value_dkk"]) / max(float(sell_position["quantity"]), 1.0)
    buy_estimate = float(buy_position["market_value_dkk"]) / max(float(buy_position["quantity"]), 1.0)
    manual_sell_id = _insert_manual_order(
        connection,
        symbol=sell_position["symbol"],
        action="SELL",
        mode="simulation",
        quantity=min(max(float(sell_position["quantity"]) * 0.05, 1.0), float(sell_position["quantity"])),
        price_local=float(sell_position["current_price_local"]),
        currency=str(sell_position["currency"]),
        estimated_value_dkk=sell_estimate,
    )
    manual_buy_id = _insert_manual_order(
        connection,
        symbol=buy_position["symbol"],
        action="BUY",
        mode="simulation",
        quantity=1.0,
        price_local=float(buy_position["current_price_local"]),
        currency=str(buy_position["currency"]),
        estimated_value_dkk=buy_estimate,
    )
    execute_order(manual_sell_id, config=config, connection=connection)
    execute_order(manual_buy_id, config=config, connection=connection)
    execution_orders = fetch_execution_orders(connection, limit=10)
    trade_count = connection.execute("SELECT COUNT(*) AS count_rows FROM trade_ledger").fetchone()["count_rows"]
    audit_export = export_audit_bundle(str(export_dir), config=config, connection=connection)
    scheduler_result = run_scheduler_cycle(
        config=config,
        connection=connection,
        force_mock=True,
        force_decision=True,
    )

    assert queue_result["status"] == "ok", f"Unexpected queue status: {queue_result['status']}"
    assert len(queued_orders) >= 1, f"Expected at least one queued order, got {len(queued_orders)}"
    assert len(execution_orders) >= 2, "Expected execution orders to persist"
    assert sum(1 for order in execution_orders if order["status"] == "executed") >= 2, "Expected executed simulation orders"
    assert trade_count >= 2, "Expected simulated ledger entries to be written"
    assert scheduler_result["status"] == "ok", f"Scheduler cycle failed: {scheduler_result}"
    for file_path in audit_export["files"].values():
        assert Path(file_path).exists(), f"Missing export file {file_path}"

    print("Phase 5 validation passed.")
    print(f"Imported source positions: {result.source_positions}")
    print(f"Excluded positions: {result.excluded_positions}")
    print(f"Seed report id: {report_id}")
    print(f"Execution orders created: {len(queued_orders)}")
    print(f"Executed simulation orders: {sum(1 for order in execution_orders if order['status'] == 'executed')}")
    print(f"Trade ledger rows: {trade_count}")
    print(f"Audit export dir: {audit_export['output_dir']}")
    print(f"Scheduler generated decision: {scheduler_result['generated_decision']}")

    connection.close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
