from __future__ import annotations

import json
import sys
import uuid
from datetime import UTC, datetime, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from saxo_daytrader_xai import saxo_openapi
from saxo_daytrader_xai.config import load_config
from saxo_daytrader_xai.db import connect, init_db
from saxo_daytrader_xai.execution_engine import execute_order, fetch_execution_orders, queue_and_maybe_execute_latest_report
from saxo_daytrader_xai.importer import sync_portfolio
from saxo_daytrader_xai.portfolio import fetch_portfolio_positions


def _insert_completed_report(connection, suggestions: list[dict[str, object]]) -> int:
    created_at = datetime.now(UTC).isoformat(timespec="seconds")
    report_json = {
        "report_title": "Phase 29 Integer Quantity Validation",
        "analysis_window_active": True,
        "goal": "Validation run",
        "market_regime": {"summary": "Synthetic validation context"},
        "portfolio_assessment": {"summary": "Whole-share enforcement check"},
        "reasoning_steps": ["Create fractional target suggestions", "Verify queued orders are whole shares"],
        "risk_rules_check": ["Whole-share sizing enforced"],
        "watchlist_focus": [],
        "suggested_trades": suggestions,
        "execution_notes": ["Generated by scripts/validate_phase29.py"],
        "daily_target_assessment": "Validation only.",
    }
    cursor = connection.execute(
        """
        INSERT INTO decision_reports (
            created_at, report_date, batch_id, model, status, analysis_window_active,
            response_id, prompt_text, request_json, response_json, report_json, error_text
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            created_at,
            created_at[:10],
            "phase29-validation",
            "mock-validator",
            "completed",
            1,
            "phase29-validation",
            json.dumps({"source": "validate_phase29"}, ensure_ascii=False, sort_keys=True),
            json.dumps({"source": "validate_phase29"}, ensure_ascii=False, sort_keys=True),
            json.dumps({"source": "validate_phase29"}, ensure_ascii=False, sort_keys=True),
            json.dumps(report_json, ensure_ascii=False, sort_keys=True),
            None,
        ),
    )
    connection.commit()
    return int(cursor.lastrowid)


class _FakeResponse:
    def __init__(self, payload: dict):
        self._payload = payload

    def raise_for_status(self) -> None:
        return None

    def json(self) -> dict:
        return self._payload


def main() -> int:
    config = load_config(ROOT / "config.yaml")
    db_path = Path("/tmp") / f"saxo_daytrader_phase29_{uuid.uuid4().hex}.db"
    session_path = Path("/tmp") / f"saxo_daytrader_phase29_session_{uuid.uuid4().hex}.json"
    config["portfolio"]["database_path"] = str(db_path)
    config["execution"]["mode"] = "simulation"
    config["execution"]["auto_execute_simulation"] = False

    result = sync_portfolio(config)
    connection = connect(config["portfolio"]["database_path"])
    init_db(connection)
    positions = fetch_portfolio_positions(connection)
    sell_position = next(row for row in positions if row["symbol"] == "MSTR:xnas")
    buy_position = next(row for row in positions if row["symbol"] != "MSTR:xnas")

    report_id = _insert_completed_report(
        connection,
        [
            {
                "action": "SELL",
                "symbol": sell_position["symbol"],
                "target_weight_pct": 3.0,
                "quantity_hint": "Fractional trim candidate",
                "confidence": 0.8,
                "priority": "high",
                "rationale": "Validation sell path",
                "risk_notes": ["Validation only"],
            },
            {
                "action": "BUY",
                "symbol": buy_position["symbol"],
                "target_weight_pct": 5.0,
                "quantity_hint": "Fractional buy candidate",
                "confidence": 0.75,
                "priority": "medium",
                "rationale": "Validation buy path",
                "risk_notes": ["Validation only"],
            },
        ],
    )
    queue_result = queue_and_maybe_execute_latest_report(config=config, connection=connection)
    queued_orders = fetch_execution_orders(connection, limit=10)
    queued_relevant = [row for row in queued_orders if row["report_id"] == report_id]

    assert queue_result["status"] == "ok", queue_result
    assert queued_relevant, queued_relevant
    assert all(abs(float(row["quantity"]) - round(float(row["quantity"]))) <= 1e-9 for row in queued_relevant), queued_relevant

    config["execution"]["mode"] = "live"
    config["app"]["dry_run"] = False
    config["saxo"]["session_path"] = str(session_path)
    session_path.write_text(
        json.dumps(
            {
                "environment": "sim",
                "auth_mode": "pkce",
                "account_key": config["saxo"]["account_key"],
                "access_token": "test-access-token",
                "refresh_token": "test-refresh-token",
                "access_token_expires_at": (datetime.now(UTC) + timedelta(hours=1)).isoformat(timespec="seconds"),
                "refresh_token_expires_at": (datetime.now(UTC) + timedelta(days=30)).isoformat(timespec="seconds"),
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    live_cursor = connection.execute(
        """
        INSERT INTO execution_orders (
            created_at, report_id, symbol, action, mode, status, adapter,
            requested_weight_pct, quantity, price_local, currency, estimated_value_dkk,
            approval_required, request_json, execution_result_json, error_text
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            datetime.now(UTC).isoformat(timespec="seconds"),
            None,
            buy_position["symbol"],
            "BUY",
            "live",
            "pending_approval",
            "saxo",
            0.05,
            3.7,
            float(buy_position["current_price_local"]),
            str(buy_position["currency"]),
            1000.0,
            1,
            json.dumps({"source": "validate_phase29_live"}, ensure_ascii=False, sort_keys=True),
            None,
            None,
        ),
    )
    live_order_id = int(live_cursor.lastrowid)
    connection.commit()

    original_get = saxo_openapi.requests.get
    original_post = saxo_openapi.requests.post
    seen_payloads: list[dict] = []

    def fake_get(url: str, **kwargs):
        if url.endswith("/ref/v1/instruments"):
            return _FakeResponse(
                {
                    "Data": [
                        {
                            "Identifier": 211,
                            "AssetType": "Stock",
                            "ExchangeId": buy_position["symbol"].split(":", 1)[1].upper(),
                            "Symbol": buy_position["symbol"].split(":", 1)[0].upper(),
                            "Description": buy_position["instrument_name"],
                            "TradableAs": ["Stock"],
                            "CurrencyCode": buy_position["currency"],
                        }
                    ]
                }
            )
        raise AssertionError(f"Unexpected GET {url}")

    def fake_post(url: str, **kwargs):
        seen_payloads.append(kwargs.get("json", {}))
        if url.endswith("/trade/v2/orders/precheck"):
            return _FakeResponse({"EstimatedTotalCost": 12.34, "OrderId": None})
        if url.endswith("/trade/v2/orders"):
            return _FakeResponse({"OrderId": "SIM-ORDER-129", "Status": "Placed"})
        raise AssertionError(f"Unexpected POST {url}")

    saxo_openapi.requests.get = fake_get
    saxo_openapi.requests.post = fake_post
    try:
        live_result = execute_order(live_order_id, config=config, connection=connection, approved=True)
    finally:
        saxo_openapi.requests.get = original_get
        saxo_openapi.requests.post = original_post

    stored_live = connection.execute("SELECT quantity, status, execution_result_json FROM execution_orders WHERE id = ?", (live_order_id,)).fetchone()
    payload_amounts = [payload.get("Amount") for payload in seen_payloads if payload.get("Amount") is not None]

    assert live_result["status"] == "submitted_to_broker", live_result
    assert abs(float(stored_live["quantity"]) - 3.0) <= 1e-9, dict(stored_live)
    assert payload_amounts == [3, 3], payload_amounts

    print("Phase 29 validation passed.")
    print(f"Imported source positions: {result.source_positions}")
    print(f"Excluded positions: {result.excluded_positions}")
    print(f"Queued whole-share orders: {len(queued_relevant)}")
    print(f"Live payload amounts: {payload_amounts}")
    print(f"Stored live quantity: {float(stored_live['quantity']):.0f}")
    connection.close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
