from __future__ import annotations

import json
import re
import sqlite3
from datetime import UTC, datetime
from pathlib import Path
from typing import Any


AUTOINCREMENT_TABLES = {
    "audit_log",
    "analysis_pulses",
    "decision_reports",
    "execution_fills",
    "execution_order_events",
    "execution_orders",
    "lot_realizations",
    "notification_deliveries",
    "portfolio_reconciliation_adjustments",
    "portfolio_value_history",
    "position_snapshots",
    "scheduler_cycle_history",
    "strategy_journal_entries",
    "swing_position_targets",
    "swing_sentiment_snapshots",
    "trading_manager_runs",
    "trade_ledger",
}


class PostgresCursor:
    def __init__(self, cursor: Any, *, lastrowid: int | None = None):
        self._cursor = cursor
        self.lastrowid = lastrowid

    @property
    def rowcount(self) -> int:
        return int(getattr(self._cursor, "rowcount", 0) or 0)

    def fetchone(self) -> Any:
        return self._cursor.fetchone()

    def fetchall(self) -> list[Any]:
        return self._cursor.fetchall()


class PostgresConnection:
    dialect = "postgres"

    def __init__(self, dsn: str):
        try:
            import psycopg
            from psycopg.rows import dict_row
        except ImportError as exc:  # pragma: no cover - dependency error is explicit at runtime
            raise RuntimeError("PostgreSQL support requires psycopg; run `pip install -r requirements.txt`.") from exc

        self._connection = psycopg.connect(dsn, row_factory=dict_row)

    def execute(self, sql: str, parameters: tuple[Any, ...] | list[Any] = ()) -> PostgresCursor:
        translated_sql, returning_id = _translate_postgres_sql(sql)
        cursor = self._connection.execute(translated_sql, parameters)
        lastrowid = None
        if returning_id:
            row = cursor.fetchone()
            if row is not None:
                lastrowid = int(row["id"])
        return PostgresCursor(cursor, lastrowid=lastrowid)

    def executemany(self, sql: str, parameters_seq: list[tuple[Any, ...]] | tuple[tuple[Any, ...], ...]) -> PostgresCursor:
        translated_sql, returning_id = _translate_postgres_sql(sql)
        if returning_id:
            translated_sql = re.sub(r"\s+RETURNING\s+id\s*$", "", translated_sql, flags=re.IGNORECASE)
        cursor = self._connection.cursor()
        cursor.executemany(translated_sql, parameters_seq)
        return PostgresCursor(cursor)

    def executescript(self, sql_script: str) -> None:
        for statement in _split_sql_script(_translate_postgres_schema(sql_script)):
            self.execute(statement)

    def commit(self) -> None:
        self._connection.commit()

    def rollback(self) -> None:
        self._connection.rollback()

    def close(self) -> None:
        self._connection.close()

    def __enter__(self) -> "PostgresConnection":
        return self

    def __exit__(self, exc_type: Any, exc: Any, traceback: Any) -> None:
        if exc_type is None:
            self.commit()
        else:
            self.rollback()
        self.close()


def _is_postgres_dsn(value: str) -> bool:
    return value.startswith(("postgresql://", "postgres://"))


def _is_postgres_connection(connection: Any) -> bool:
    return getattr(connection, "dialect", "sqlite") == "postgres"


def try_postgres_advisory_lock(connection: Any, key: str) -> bool:
    if not _is_postgres_connection(connection):
        return True
    row = connection.execute("SELECT pg_try_advisory_lock(hashtext(?)) AS locked", (key,)).fetchone()
    return bool(row and row["locked"])


def release_postgres_advisory_lock(connection: Any, key: str) -> None:
    if not _is_postgres_connection(connection):
        return
    connection.execute("SELECT pg_advisory_unlock(hashtext(?)) AS unlocked", (key,))


def _split_sql_script(sql_script: str) -> list[str]:
    return [statement.strip() for statement in sql_script.split(";") if statement.strip()]


def _translate_placeholders(sql: str) -> str:
    return sql.replace("?", "%s")


def _insert_table_name(sql: str) -> str | None:
    match = re.match(r"\s*INSERT\s+INTO\s+([a-zA-Z_][a-zA-Z0-9_]*)", sql, flags=re.IGNORECASE)
    return match.group(1) if match else None


def _translate_postgres_sql(sql: str) -> tuple[str, bool]:
    stripped = sql.strip()
    table_name = _insert_table_name(stripped)
    returning_id = (
        table_name in AUTOINCREMENT_TABLES
        and " RETURNING " not in stripped.upper()
        and " ON CONFLICT " not in stripped.upper()
    )
    translated = _translate_placeholders(stripped)
    if returning_id:
        translated = f"{translated} RETURNING id"
    return translated, returning_id


def _translate_postgres_schema(schema_sql: str) -> str:
    translated = schema_sql.replace("INTEGER PRIMARY KEY AUTOINCREMENT", "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
    translated = translated.replace("REAL", "DOUBLE PRECISION")
    return translated


def connect(database_path: str | Path) -> sqlite3.Connection | PostgresConnection:
    database_value = str(database_path)
    if _is_postgres_dsn(database_value):
        return PostgresConnection(database_value)
    connection = sqlite3.connect(database_value)
    connection.row_factory = sqlite3.Row
    connection.execute("PRAGMA foreign_keys = ON")
    return connection


def init_db(connection: sqlite3.Connection) -> None:
    schema_sql = """
        CREATE TABLE IF NOT EXISTS import_batches (
            batch_id TEXT PRIMARY KEY,
            imported_at TEXT NOT NULL,
            source_csv TEXT NOT NULL,
            source_position_count INTEGER NOT NULL,
            imported_position_count INTEGER NOT NULL,
            excluded_position_count INTEGER NOT NULL,
            notes TEXT
        );

        CREATE TABLE IF NOT EXISTS position_snapshots (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            batch_id TEXT NOT NULL,
            imported_at TEXT NOT NULL,
            instrument_name TEXT NOT NULL,
            symbol TEXT NOT NULL,
            isin TEXT,
            quantity REAL NOT NULL,
            currency TEXT NOT NULL,
            open_price_local REAL,
            current_price_local REAL,
            cost_basis_local REAL,
            cost_basis_dkk REAL NOT NULL,
            market_value_local REAL,
            market_value_dkk REAL NOT NULL,
            unrealised_pnl_dkk REAL NOT NULL,
            daily_pnl_dkk REAL,
            allocation_pct REAL,
            status TEXT,
            account_name TEXT,
            asset_class TEXT,
            market_status TEXT,
            value_date TEXT,
            source_csv TEXT NOT NULL,
            excluded INTEGER NOT NULL DEFAULT 0,
            exclusion_reason TEXT,
            raw_payload_json TEXT NOT NULL,
            FOREIGN KEY(batch_id) REFERENCES import_batches(batch_id)
        );

        CREATE INDEX IF NOT EXISTS idx_position_snapshots_batch
        ON position_snapshots(batch_id, excluded);

        CREATE TABLE IF NOT EXISTS position_lots (
            lot_id TEXT PRIMARY KEY,
            batch_id TEXT NOT NULL,
            created_at TEXT NOT NULL,
            acquired_at TEXT,
            symbol TEXT NOT NULL,
            isin TEXT,
            figi TEXT,
            instrument_name TEXT NOT NULL,
            quantity_original REAL NOT NULL,
            currency TEXT NOT NULL,
            cost_basis_total_local REAL,
            cost_basis_total_dkk REAL NOT NULL,
            fx_rate_to_dkk REAL NOT NULL,
            source_type TEXT NOT NULL,
            source_reference TEXT,
            raw_payload_json TEXT NOT NULL,
            FOREIGN KEY(batch_id) REFERENCES import_batches(batch_id)
        );

        CREATE INDEX IF NOT EXISTS idx_position_lots_symbol
        ON position_lots(symbol, created_at);

        CREATE TABLE IF NOT EXISTS trade_ledger (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            created_at TEXT NOT NULL,
            symbol TEXT NOT NULL,
            isin TEXT,
            figi TEXT,
            instrument_name TEXT,
            side TEXT NOT NULL,
            quantity REAL NOT NULL,
            price_local REAL NOT NULL,
            currency TEXT NOT NULL,
            gross_amount_dkk REAL NOT NULL,
            commission_dkk REAL NOT NULL,
            tax_dkk REAL NOT NULL,
            net_amount_dkk REAL NOT NULL,
            mode TEXT NOT NULL,
            status TEXT NOT NULL,
            notes TEXT,
            portfolio_before_json TEXT,
            portfolio_after_json TEXT,
            decision_context_json TEXT
        );

        CREATE TABLE IF NOT EXISTS lot_realizations (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            created_at TEXT NOT NULL,
            ledger_id INTEGER NOT NULL,
            lot_id TEXT NOT NULL,
            symbol TEXT NOT NULL,
            quantity_sold REAL NOT NULL,
            cost_basis_allocated_local REAL,
            cost_basis_allocated_dkk REAL NOT NULL,
            proceeds_allocated_dkk REAL NOT NULL,
            realised_gain_dkk REAL NOT NULL,
            raw_payload_json TEXT NOT NULL,
            FOREIGN KEY(ledger_id) REFERENCES trade_ledger(id),
            FOREIGN KEY(lot_id) REFERENCES position_lots(lot_id)
        );

        CREATE INDEX IF NOT EXISTS idx_lot_realizations_lot
        ON lot_realizations(lot_id, ledger_id);

        CREATE TABLE IF NOT EXISTS decision_reports (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            created_at TEXT NOT NULL,
            report_date TEXT NOT NULL,
            batch_id TEXT,
            model TEXT NOT NULL,
            status TEXT NOT NULL,
            analysis_window_active INTEGER NOT NULL DEFAULT 0,
            response_id TEXT,
            prompt_text TEXT NOT NULL,
            request_json TEXT NOT NULL,
            response_json TEXT,
            report_json TEXT,
            error_text TEXT
        );

        CREATE INDEX IF NOT EXISTS idx_decision_reports_created
        ON decision_reports(created_at DESC);

        CREATE TABLE IF NOT EXISTS execution_orders (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            created_at TEXT NOT NULL,
            report_id INTEGER,
            symbol TEXT NOT NULL,
            action TEXT NOT NULL,
            order_type TEXT NOT NULL DEFAULT 'Market',
            mode TEXT NOT NULL,
            status TEXT NOT NULL,
            adapter TEXT NOT NULL,
            requested_weight_pct REAL,
            quantity REAL,
            price_local REAL,
            limit_price_local REAL,
            stop_price_local REAL,
            currency TEXT,
            estimated_value_dkk REAL,
            approval_required INTEGER NOT NULL DEFAULT 0,
            approved_at TEXT,
            ledger_id INTEGER,
            parent_execution_order_id INTEGER,
            strategy_type TEXT,
            strategy_session TEXT,
            strategy_key TEXT,
            strategy_role TEXT,
            request_json TEXT NOT NULL,
            execution_result_json TEXT,
            error_text TEXT,
            FOREIGN KEY(report_id) REFERENCES decision_reports(id),
            FOREIGN KEY(ledger_id) REFERENCES trade_ledger(id),
            FOREIGN KEY(parent_execution_order_id) REFERENCES execution_orders(id)
        );

        CREATE INDEX IF NOT EXISTS idx_execution_orders_report
        ON execution_orders(report_id, status);

        CREATE TABLE IF NOT EXISTS execution_fills (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            created_at TEXT NOT NULL,
            execution_order_id INTEGER NOT NULL,
            broker_order_id TEXT,
            symbol TEXT NOT NULL,
            side TEXT NOT NULL,
            fill_status TEXT NOT NULL,
            cumulative_quantity REAL NOT NULL,
            delta_quantity REAL NOT NULL,
            average_price_local REAL NOT NULL,
            currency TEXT NOT NULL,
            ledger_id INTEGER,
            raw_payload_json TEXT NOT NULL,
            FOREIGN KEY(execution_order_id) REFERENCES execution_orders(id),
            FOREIGN KEY(ledger_id) REFERENCES trade_ledger(id)
        );

        CREATE INDEX IF NOT EXISTS idx_execution_fills_order
        ON execution_fills(execution_order_id, cumulative_quantity, created_at);

        CREATE TABLE IF NOT EXISTS execution_order_events (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            created_at TEXT NOT NULL,
            execution_order_id INTEGER NOT NULL,
            broker_order_id TEXT,
            event_type TEXT NOT NULL,
            broker_status TEXT,
            broker_substatus TEXT,
            broker_quantity REAL,
            broker_price_local REAL,
            event_signature TEXT NOT NULL,
            raw_payload_json TEXT NOT NULL,
            FOREIGN KEY(execution_order_id) REFERENCES execution_orders(id)
        );

        CREATE UNIQUE INDEX IF NOT EXISTS idx_execution_order_events_signature
        ON execution_order_events(event_signature);

        CREATE INDEX IF NOT EXISTS idx_execution_order_events_order
        ON execution_order_events(execution_order_id, created_at DESC);

        CREATE TABLE IF NOT EXISTS notification_deliveries (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            created_at TEXT NOT NULL,
            summary_date TEXT NOT NULL,
            channel TEXT NOT NULL,
            status TEXT NOT NULL,
            subject TEXT NOT NULL,
            message_text TEXT NOT NULL,
            payload_json TEXT NOT NULL,
            error_text TEXT
        );

        CREATE INDEX IF NOT EXISTS idx_notification_deliveries_summary
        ON notification_deliveries(summary_date, channel, status, created_at DESC);

        CREATE TABLE IF NOT EXISTS notification_channel_state (
            channel TEXT PRIMARY KEY,
            summary_date TEXT,
            last_attempt_at TEXT,
            next_attempt_after TEXT,
            attempt_count INTEGER NOT NULL DEFAULT 0,
            last_status TEXT,
            last_error_text TEXT
        );

        CREATE TABLE IF NOT EXISTS notification_alert_state (
            scope_key TEXT PRIMARY KEY,
            severity TEXT NOT NULL,
            last_sent_at TEXT,
            last_alert_key TEXT,
            last_summary_kind TEXT,
            last_delivery_id INTEGER
        );

        CREATE TABLE IF NOT EXISTS scheduler_status (
            singleton_key TEXT PRIMARY KEY,
            started_at TEXT,
            last_heartbeat_at TEXT,
            last_cycle_started_at TEXT,
            last_cycle_completed_at TEXT,
            last_cycle_status TEXT,
            last_cycle_json TEXT,
            scheduler_pid INTEGER
        );

        CREATE TABLE IF NOT EXISTS scheduler_cycle_history (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            started_at TEXT NOT NULL,
            completed_at TEXT,
            status TEXT NOT NULL,
            analysis_window_active INTEGER NOT NULL DEFAULT 0,
            generated_decision INTEGER NOT NULL DEFAULT 0,
            queue_status TEXT,
            notifications_status TEXT,
            broker_alerts_status TEXT,
            cycle_json TEXT NOT NULL
        );

        CREATE INDEX IF NOT EXISTS idx_scheduler_cycle_history_started
        ON scheduler_cycle_history(started_at DESC);

        CREATE TABLE IF NOT EXISTS runtime_settings (
            key TEXT PRIMARY KEY,
            value_json TEXT NOT NULL,
            updated_at TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS portfolio_price_snapshots (
            symbol TEXT PRIMARY KEY,
            updated_at TEXT NOT NULL,
            baseline_session_date TEXT NOT NULL,
            baseline_at TEXT,
            current_price_local REAL,
            current_fx_rate_to_dkk REAL,
            previous_close_local REAL,
            change_pct REAL,
            currency TEXT,
            source TEXT,
            status TEXT,
            baseline_price_local REAL,
            baseline_fx_rate_to_dkk REAL
        );

        CREATE INDEX IF NOT EXISTS idx_portfolio_price_snapshots_baseline
        ON portfolio_price_snapshots(baseline_session_date, updated_at DESC);

        CREATE TABLE IF NOT EXISTS portfolio_value_history (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            recorded_at TEXT NOT NULL,
            snapshot_type TEXT NOT NULL,
            baseline_session_date TEXT,
            batch_id TEXT,
            total_market_value_dkk REAL NOT NULL,
            invested_market_value_dkk REAL NOT NULL,
            cash_balance_dkk REAL NOT NULL,
            total_cost_basis_dkk REAL NOT NULL,
            total_unrealised_pnl_dkk REAL NOT NULL,
            total_daily_pnl_dkk REAL NOT NULL,
            position_count INTEGER NOT NULL,
            source TEXT,
            raw_payload_json TEXT NOT NULL
        );

        CREATE INDEX IF NOT EXISTS idx_portfolio_value_history_recorded
        ON portfolio_value_history(recorded_at DESC);

        CREATE TABLE IF NOT EXISTS broker_position_snapshots (
            symbol TEXT PRIMARY KEY,
            updated_at TEXT NOT NULL,
            instrument_name TEXT,
            isin TEXT,
            uic INTEGER,
            asset_type TEXT,
            quantity REAL NOT NULL,
            currency TEXT,
            open_price_local REAL,
            open_price_including_costs_local REAL,
            execution_time_open TEXT,
            value_date TEXT,
            market_state TEXT,
            can_be_closed INTEGER,
            raw_payload_json TEXT NOT NULL
        );

        CREATE INDEX IF NOT EXISTS idx_broker_position_snapshots_updated
        ON broker_position_snapshots(updated_at DESC);

        CREATE TABLE IF NOT EXISTS broker_balance_snapshots (
            singleton_key TEXT PRIMARY KEY,
            updated_at TEXT NOT NULL,
            currency TEXT,
            cash_available_for_trading REAL,
            margin_available_for_trading REAL,
            cash_balance REAL,
            transactions_not_booked REAL,
            settlement_value REAL,
            total_value REAL,
            raw_payload_json TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS broker_account_snapshots (
            singleton_key TEXT PRIMARY KEY,
            updated_at TEXT NOT NULL,
            account_key TEXT,
            account_id TEXT,
            account_currency TEXT,
            is_trial_account INTEGER,
            fractional_order_enabled INTEGER,
            fractional_order_enabled_asset_types_json TEXT,
            can_use_cash_positions_as_margin_collateral INTEGER,
            use_cash_positions_as_margin_collateral INTEGER,
            legal_asset_types_json TEXT,
            raw_payload_json TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS broker_instrument_exposures (
            symbol TEXT PRIMARY KEY,
            updated_at TEXT NOT NULL,
            uic INTEGER,
            asset_type TEXT,
            quantity REAL,
            average_open_price REAL,
            profit_loss_on_trade REAL,
            instrument_price_day_percent_change REAL,
            currency TEXT,
            calculation_reliability TEXT,
            can_be_closed INTEGER,
            raw_payload_json TEXT NOT NULL
        );

        CREATE INDEX IF NOT EXISTS idx_broker_instrument_exposures_updated
        ON broker_instrument_exposures(updated_at DESC);

        CREATE TABLE IF NOT EXISTS portfolio_reconciliation_adjustments (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            created_at TEXT NOT NULL,
            symbol TEXT NOT NULL,
            instrument_name TEXT,
            isin TEXT,
            currency TEXT,
            quantity_delta REAL NOT NULL,
            cost_basis_local_delta REAL NOT NULL,
            cost_basis_dkk_delta REAL NOT NULL,
            local_quantity_before REAL NOT NULL,
            broker_quantity_target REAL NOT NULL,
            note TEXT,
            raw_payload_json TEXT NOT NULL
        );

        CREATE INDEX IF NOT EXISTS idx_portfolio_reconciliation_adjustments_symbol
        ON portfolio_reconciliation_adjustments(symbol, created_at DESC);

        CREATE TABLE IF NOT EXISTS audit_log (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            created_at TEXT NOT NULL,
            event_type TEXT NOT NULL,
            event_json TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS analysis_pulses (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            created_at TEXT NOT NULL,
            pulse_key TEXT NOT NULL,
            pulse_kind TEXT NOT NULL,
            pulse_label TEXT NOT NULL,
            target_at_utc TEXT NOT NULL,
            report_id INTEGER,
            status TEXT NOT NULL,
            metadata_json TEXT NOT NULL,
            FOREIGN KEY(report_id) REFERENCES decision_reports(id)
        );

        CREATE UNIQUE INDEX IF NOT EXISTS idx_analysis_pulses_key_report
        ON analysis_pulses(pulse_key, report_id);

        CREATE INDEX IF NOT EXISTS idx_analysis_pulses_created
        ON analysis_pulses(created_at DESC);

        CREATE TABLE IF NOT EXISTS trading_manager_runs (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            created_at TEXT NOT NULL,
            manager_key TEXT NOT NULL,
            manager_kind TEXT NOT NULL,
            manager_label TEXT NOT NULL,
            target_at_utc TEXT NOT NULL,
            report_id INTEGER,
            status TEXT NOT NULL,
            open_exchange_codes_json TEXT NOT NULL,
            technical_json TEXT NOT NULL,
            manager_json TEXT NOT NULL,
            queue_result_json TEXT,
            error_text TEXT,
            FOREIGN KEY(report_id) REFERENCES decision_reports(id)
        );

        CREATE INDEX IF NOT EXISTS idx_trading_manager_runs_key
        ON trading_manager_runs(manager_key);

        CREATE INDEX IF NOT EXISTS idx_trading_manager_runs_created
        ON trading_manager_runs(created_at DESC);

        CREATE TABLE IF NOT EXISTS swing_sentiment_snapshots (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            created_at TEXT NOT NULL,
            report_id INTEGER NOT NULL,
            pulse_key TEXT,
            symbol TEXT NOT NULL,
            sentiment TEXT NOT NULL,
            confidence REAL NOT NULL,
            macro_bias TEXT,
            rationale TEXT NOT NULL,
            catalysts_json TEXT NOT NULL,
            risk_notes_json TEXT NOT NULL,
            source_json TEXT NOT NULL,
            FOREIGN KEY(report_id) REFERENCES decision_reports(id)
        );

        CREATE INDEX IF NOT EXISTS idx_swing_sentiment_report
        ON swing_sentiment_snapshots(report_id, symbol);

        CREATE TABLE IF NOT EXISTS swing_position_targets (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            created_at TEXT NOT NULL,
            report_id INTEGER NOT NULL,
            pulse_key TEXT,
            symbol TEXT NOT NULL,
            sentiment TEXT NOT NULL,
            action TEXT NOT NULL,
            current_weight_pct REAL NOT NULL,
            target_weight_pct REAL NOT NULL,
            current_quantity REAL NOT NULL,
            target_quantity REAL,
            estimated_delta_quantity REAL,
            estimated_value_dkk REAL,
            priority TEXT NOT NULL,
            confidence REAL NOT NULL,
            rationale TEXT NOT NULL,
            risk_json TEXT NOT NULL,
            FOREIGN KEY(report_id) REFERENCES decision_reports(id)
        );

        CREATE INDEX IF NOT EXISTS idx_swing_targets_report
        ON swing_position_targets(report_id, action, symbol);

        CREATE TABLE IF NOT EXISTS strategy_journal_entries (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            created_at TEXT NOT NULL,
            journal_date TEXT NOT NULL,
            cadence TEXT NOT NULL,
            status TEXT NOT NULL,
            summary TEXT NOT NULL,
            metrics_json TEXT NOT NULL,
            learnings_json TEXT NOT NULL,
            source_report_id INTEGER,
            FOREIGN KEY(source_report_id) REFERENCES decision_reports(id)
        );

        CREATE INDEX IF NOT EXISTS idx_strategy_journal_date
        ON strategy_journal_entries(journal_date DESC, cadence);
        """
    connection.executescript(schema_sql)
    _init_platform_access_tables(connection)
    _ensure_column(connection, "trade_ledger", "commission_local", "REAL")
    _ensure_column(connection, "trade_ledger", "figi", "TEXT")
    _ensure_column(connection, "trade_ledger", "instrument_name", "TEXT")
    _ensure_column(connection, "trade_ledger", "fx_conversion_dkk", "REAL NOT NULL DEFAULT 0")
    _ensure_column(connection, "trade_ledger", "realised_gain_dkk", "REAL NOT NULL DEFAULT 0")
    _ensure_column(connection, "trade_ledger", "cost_basis_sold_dkk", "REAL NOT NULL DEFAULT 0")
    _ensure_column(connection, "trade_ledger", "cost_basis_sold_local", "REAL NOT NULL DEFAULT 0")
    _ensure_column(connection, "trade_ledger", "realised_gain_local", "REAL NOT NULL DEFAULT 0")
    _ensure_column(connection, "trade_ledger", "fx_gain_dkk", "REAL NOT NULL DEFAULT 0")
    _ensure_column(connection, "trade_ledger", "price_gain_dkk", "REAL NOT NULL DEFAULT 0")
    _ensure_column(connection, "trade_ledger", "sale_fx_rate_to_dkk", "REAL")
    _ensure_column(connection, "trade_ledger", "cost_basis_fx_rate_to_dkk", "REAL")
    _ensure_column(connection, "trade_ledger", "tax_year", "INTEGER")
    _ensure_column(connection, "trade_ledger", "batch_id", "TEXT")
    _ensure_column(connection, "position_lots", "figi", "TEXT")
    _ensure_column(connection, "execution_orders", "broker_order_id", "TEXT")
    _ensure_column(connection, "execution_orders", "order_type", "TEXT NOT NULL DEFAULT 'Market'")
    _ensure_column(connection, "execution_orders", "limit_price_local", "REAL")
    _ensure_column(connection, "execution_orders", "stop_price_local", "REAL")
    _ensure_column(connection, "execution_orders", "parent_execution_order_id", "INTEGER")
    _ensure_column(connection, "execution_orders", "strategy_type", "TEXT")
    _ensure_column(connection, "execution_orders", "strategy_session", "TEXT")
    _ensure_column(connection, "execution_orders", "strategy_key", "TEXT")
    _ensure_column(connection, "execution_orders", "strategy_role", "TEXT")
    _ensure_column(connection, "decision_reports", "analysis_pulse_key", "TEXT")
    _ensure_column(connection, "decision_reports", "analysis_pulse_label", "TEXT")
    _ensure_column(connection, "strategy_journal_entries", "diary_json", "TEXT")
    for table_name in (
        "import_batches",
        "position_snapshots",
        "position_lots",
        "trade_ledger",
        "decision_reports",
        "execution_orders",
        "execution_fills",
        "execution_order_events",
        "broker_position_snapshots",
        "broker_balance_snapshots",
        "broker_account_snapshots",
        "broker_instrument_exposures",
        "portfolio_reconciliation_adjustments",
        "portfolio_price_snapshots",
        "portfolio_value_history",
    ):
        _ensure_column(connection, table_name, "environment_id", "TEXT NOT NULL DEFAULT 'SIM'")
        _ensure_column(connection, table_name, "account_uid", "TEXT NOT NULL DEFAULT 'SIM_DEFAULT'")
    connection.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_execution_orders_strategy
        ON execution_orders(strategy_key, status)
        """
    )
    _ensure_column(connection, "notification_deliveries", "summary_kind", "TEXT NOT NULL DEFAULT 'daily'")
    connection.commit()


def _init_platform_access_tables(connection: sqlite3.Connection | PostgresConnection) -> None:
    connection.executescript(
        """
        CREATE TABLE IF NOT EXISTS trading_environments (
            environment_id TEXT PRIMARY KEY,
            display_name TEXT NOT NULL,
            broker_environment TEXT NOT NULL,
            is_live INTEGER NOT NULL DEFAULT 0,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS trading_accounts (
            account_uid TEXT PRIMARY KEY,
            environment_id TEXT NOT NULL,
            account_key TEXT,
            account_id TEXT,
            display_name TEXT NOT NULL,
            base_currency TEXT NOT NULL DEFAULT 'DKK',
            virtual_cap_dkk REAL,
            is_active INTEGER NOT NULL DEFAULT 1,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            raw_payload_json TEXT,
            FOREIGN KEY(environment_id) REFERENCES trading_environments(environment_id)
        );

        CREATE TABLE IF NOT EXISTS app_users (
            email TEXT PRIMARY KEY,
            display_name TEXT,
            role TEXT NOT NULL DEFAULT 'viewer',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            last_seen_at TEXT
        );

        CREATE TABLE IF NOT EXISTS user_account_access (
            email TEXT NOT NULL,
            account_uid TEXT NOT NULL,
            can_view INTEGER NOT NULL DEFAULT 1,
            can_trade INTEGER NOT NULL DEFAULT 0,
            granted_by_email TEXT,
            granted_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (email, account_uid),
            FOREIGN KEY(email) REFERENCES app_users(email),
            FOREIGN KEY(account_uid) REFERENCES trading_accounts(account_uid)
        );
        """
    )
    connection.execute(
        """
        INSERT INTO trading_environments (environment_id, display_name, broker_environment, is_live)
        VALUES (?, ?, ?, ?)
        ON CONFLICT(environment_id) DO NOTHING
        """,
        ("SIM", "Saxo SIM", "sim", 0),
    )
    connection.execute(
        """
        INSERT INTO trading_environments (environment_id, display_name, broker_environment, is_live)
        VALUES (?, ?, ?, ?)
        ON CONFLICT(environment_id) DO NOTHING
        """,
        ("LIVE", "Saxo LIVE", "live", 1),
    )
    connection.execute(
        """
        INSERT INTO trading_accounts (
            account_uid, environment_id, account_key, account_id, display_name, base_currency,
            virtual_cap_dkk, is_active, raw_payload_json
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
        ON CONFLICT(account_uid) DO NOTHING
        """,
        ("SIM_DEFAULT", "SIM", None, None, "Default SIM account", "DKK", 250000.0, 1, "{}"),
    )


def _column_names(connection: sqlite3.Connection | PostgresConnection, table_name: str) -> set[str]:
    if _is_postgres_connection(connection):
        rows = connection.execute(
            """
            SELECT column_name AS name
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = ?
            """,
            (table_name,),
        ).fetchall()
        return {row["name"] for row in rows}
    return {
        row["name"] for row in connection.execute(f"PRAGMA table_info({table_name})").fetchall()
    }


def _normalize_column_definition(connection: sqlite3.Connection | PostgresConnection, definition: str) -> str:
    if not _is_postgres_connection(connection):
        return definition
    return definition.replace("REAL", "DOUBLE PRECISION")


def _ensure_column(connection: sqlite3.Connection | PostgresConnection, table_name: str, column_name: str, definition: str) -> None:
    existing_columns = _column_names(connection, table_name)
    if column_name not in existing_columns:
        connection.execute(f"ALTER TABLE {table_name} ADD COLUMN {column_name} {_normalize_column_definition(connection, definition)}")


def append_audit_log(connection: sqlite3.Connection, event_type: str, payload: dict[str, Any]) -> None:
    connection.execute(
        """
        INSERT INTO audit_log (created_at, event_type, event_json)
        VALUES (CURRENT_TIMESTAMP, ?, ?)
        """,
        (event_type, json.dumps(payload, ensure_ascii=False, sort_keys=True)),
    )
    connection.commit()


def update_scheduler_status(
    connection: sqlite3.Connection,
    *,
    started_at: str | None = None,
    last_heartbeat_at: str | None = None,
    last_cycle_started_at: str | None = None,
    last_cycle_completed_at: str | None = None,
    last_cycle_status: str | None = None,
    last_cycle_json: dict[str, Any] | None = None,
    scheduler_pid: int | None = None,
) -> None:
    existing = connection.execute(
        "SELECT * FROM scheduler_status WHERE singleton_key = 'main'"
    ).fetchone()
    if existing is None:
        connection.execute(
            """
            INSERT INTO scheduler_status (
                singleton_key, started_at, last_heartbeat_at, last_cycle_started_at,
                last_cycle_completed_at, last_cycle_status, last_cycle_json, scheduler_pid
            ) VALUES ('main', ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                started_at,
                last_heartbeat_at,
                last_cycle_started_at,
                last_cycle_completed_at,
                last_cycle_status,
                json.dumps(last_cycle_json, ensure_ascii=False, sort_keys=True) if last_cycle_json is not None else None,
                scheduler_pid,
            ),
        )
    else:
        row = dict(existing)
        connection.execute(
            """
            UPDATE scheduler_status
            SET started_at = ?,
                last_heartbeat_at = ?,
                last_cycle_started_at = ?,
                last_cycle_completed_at = ?,
                last_cycle_status = ?,
                last_cycle_json = ?,
                scheduler_pid = ?
            WHERE singleton_key = 'main'
            """,
            (
                started_at if started_at is not None else row["started_at"],
                last_heartbeat_at if last_heartbeat_at is not None else row["last_heartbeat_at"],
                last_cycle_started_at if last_cycle_started_at is not None else row["last_cycle_started_at"],
                last_cycle_completed_at if last_cycle_completed_at is not None else row["last_cycle_completed_at"],
                last_cycle_status if last_cycle_status is not None else row["last_cycle_status"],
                json.dumps(last_cycle_json, ensure_ascii=False, sort_keys=True) if last_cycle_json is not None else row["last_cycle_json"],
                scheduler_pid if scheduler_pid is not None else row["scheduler_pid"],
            ),
        )
    connection.commit()


def fetch_scheduler_status(connection: sqlite3.Connection) -> dict[str, Any] | None:
    row = connection.execute(
        "SELECT * FROM scheduler_status WHERE singleton_key = 'main'"
    ).fetchone()
    if row is None:
        return None
    record = dict(row)
    record["last_cycle_json"] = json.loads(record["last_cycle_json"]) if record.get("last_cycle_json") else None
    return record


def record_scheduler_cycle(
    connection: sqlite3.Connection,
    *,
    started_at: str,
    completed_at: str | None,
    status: str,
    analysis_window_active: bool,
    generated_decision: bool,
    queue_status: str | None,
    notifications_status: str | None,
    broker_alerts_status: str | None,
    cycle_json: dict[str, Any],
) -> int:
    cursor = connection.execute(
        """
        INSERT INTO scheduler_cycle_history (
            started_at, completed_at, status, analysis_window_active, generated_decision,
            queue_status, notifications_status, broker_alerts_status, cycle_json
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            started_at,
            completed_at,
            status,
            1 if analysis_window_active else 0,
            1 if generated_decision else 0,
            queue_status,
            notifications_status,
            broker_alerts_status,
            json.dumps(cycle_json, ensure_ascii=False, sort_keys=True),
        ),
    )
    connection.commit()
    return int(cursor.lastrowid)


def fetch_scheduler_cycles(connection: sqlite3.Connection, limit: int = 20) -> list[dict[str, Any]]:
    rows = connection.execute(
        """
        SELECT *
        FROM scheduler_cycle_history
        ORDER BY id DESC
        LIMIT ?
        """,
        (limit,),
    ).fetchall()
    output: list[dict[str, Any]] = []
    for row in rows:
        record = dict(row)
        record["cycle_json"] = json.loads(record["cycle_json"]) if record.get("cycle_json") else None
        output.append(record)
    return output


def prune_scheduler_cycles(
    connection: sqlite3.Connection,
    *,
    keep_max_rows: int | None = None,
    keep_since_started_at: str | None = None,
) -> int:
    deleted_rows = 0
    if keep_since_started_at:
        cursor = connection.execute(
            """
            DELETE FROM scheduler_cycle_history
            WHERE started_at < ?
            """,
            (keep_since_started_at,),
        )
        deleted_rows += int(cursor.rowcount or 0)
    if keep_max_rows is not None and keep_max_rows > 0:
        cursor = connection.execute(
            """
            DELETE FROM scheduler_cycle_history
            WHERE id NOT IN (
                SELECT id
                FROM scheduler_cycle_history
                ORDER BY id DESC
                LIMIT ?
            )
            """,
            (keep_max_rows,),
        )
        deleted_rows += int(cursor.rowcount or 0)
    connection.commit()
    return deleted_rows


def record_analysis_pulse(
    connection: sqlite3.Connection,
    *,
    pulse: dict[str, Any] | None,
    report_id: int | None,
    status: str,
) -> int | None:
    if not pulse:
        return None
    cursor = connection.execute(
        """
        INSERT INTO analysis_pulses (
            created_at, pulse_key, pulse_kind, pulse_label, target_at_utc,
            report_id, status, metadata_json
        ) VALUES (CURRENT_TIMESTAMP, ?, ?, ?, ?, ?, ?, ?)
        ON CONFLICT(pulse_key, report_id) DO NOTHING
        """,
        (
            str(pulse["key"]),
            str(pulse["kind"]),
            str(pulse["label"]),
            str(pulse["target_at_utc"]),
            report_id,
            status,
            json.dumps(pulse, ensure_ascii=False, sort_keys=True),
        ),
    )
    connection.commit()
    return int(cursor.lastrowid) if cursor.lastrowid else None


def _parse_utc_datetime(value: str | None) -> datetime | None:
    if not value:
        return None
    try:
        parsed = datetime.fromisoformat(str(value).replace("Z", "+00:00"))
    except ValueError:
        return None
    if parsed.tzinfo is None:
        return parsed.replace(tzinfo=UTC)
    return parsed.astimezone(UTC)


def has_trading_manager_run(connection: sqlite3.Connection, manager_key: str) -> bool:
    row = connection.execute(
        """
        SELECT id
        FROM trading_manager_runs
        WHERE manager_key = ?
          AND status NOT LIKE 'deferred_%'
        LIMIT 1
        """,
        (manager_key,),
    ).fetchone()
    if row is not None:
        return True

    row = connection.execute(
        """
        SELECT status, manager_json
        FROM trading_manager_runs
        WHERE manager_key = ?
          AND status LIKE 'deferred_%'
        ORDER BY created_at DESC, id DESC
        LIMIT 1
        """,
        (manager_key,),
    ).fetchone()
    if row is None:
        return False
    try:
        manager_json = json.loads(row["manager_json"]) if row["manager_json"] else {}
    except ValueError:
        manager_json = {}
    next_attempt_at = _parse_utc_datetime((manager_json.get("backoff") or {}).get("next_attempt_at"))
    return bool(next_attempt_at and next_attempt_at > datetime.now(UTC))


def record_trading_manager_run(
    connection: sqlite3.Connection,
    *,
    manager_pulse: dict[str, Any],
    report_id: int | None,
    status: str,
    open_exchange_codes: list[str],
    technical: dict[str, Any],
    manager: dict[str, Any],
    queue_result: dict[str, Any] | None = None,
    error_text: str | None = None,
) -> int:
    cursor = connection.execute(
        """
        INSERT INTO trading_manager_runs (
            created_at, manager_key, manager_kind, manager_label, target_at_utc,
            report_id, status, open_exchange_codes_json, technical_json,
            manager_json, queue_result_json, error_text
        ) VALUES (CURRENT_TIMESTAMP, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            str(manager_pulse["key"]),
            str(manager_pulse["kind"]),
            str(manager_pulse["label"]),
            str(manager_pulse["target_at_utc"]),
            report_id,
            status,
            json.dumps(open_exchange_codes, ensure_ascii=False, sort_keys=True),
            json.dumps(technical, ensure_ascii=False, sort_keys=True),
            json.dumps(manager, ensure_ascii=False, sort_keys=True),
            json.dumps(queue_result, ensure_ascii=False, sort_keys=True) if queue_result is not None else None,
            error_text,
        ),
    )
    connection.commit()
    return int(cursor.lastrowid) if cursor.lastrowid else 0


def fetch_latest_trading_manager_run(connection: sqlite3.Connection) -> dict[str, Any] | None:
    row = connection.execute(
        """
        SELECT *
        FROM trading_manager_runs
        ORDER BY created_at DESC, id DESC
        LIMIT 1
        """
    ).fetchone()
    if row is None:
        return None
    record = dict(row)
    for key in ("open_exchange_codes_json", "technical_json", "manager_json", "queue_result_json"):
        output_key = key.removesuffix("_json")
        record[output_key] = json.loads(record[key]) if record.get(key) else None
    return record


def record_swing_plan_snapshot(
    connection: sqlite3.Connection,
    *,
    report_id: int,
    report_json: dict[str, Any],
) -> None:
    strategy_plan = dict(report_json.get("strategy_plan") or {})
    pulse = dict(report_json.get("analysis_pulse") or {})
    pulse_key = pulse.get("key")
    created_at = str(report_json.get("created_at") or datetime_now_iso())
    sentiment_rows = []
    for row in strategy_plan.get("sentiment_universe", []) or []:
        sentiment_rows.append(
            (
                created_at,
                report_id,
                pulse_key,
                str(row.get("symbol") or ""),
                str(row.get("sentiment") or "HOLD"),
                float(row.get("confidence") or 0.0),
                str(row.get("macro_bias") or ""),
                str(row.get("rationale") or ""),
                json.dumps(row.get("catalysts") or [], ensure_ascii=False, sort_keys=True),
                json.dumps(row.get("risk_notes") or [], ensure_ascii=False, sort_keys=True),
                json.dumps(row, ensure_ascii=False, sort_keys=True),
            )
        )
    target_rows = []
    for row in strategy_plan.get("position_targets", []) or []:
        target_rows.append(
            (
                created_at,
                report_id,
                pulse_key,
                str(row.get("symbol") or ""),
                str(row.get("sentiment") or "HOLD"),
                str(row.get("action") or "HOLD"),
                float(row.get("current_weight_pct") or 0.0),
                float(row.get("target_weight_pct") or 0.0),
                float(row.get("current_quantity") or 0.0),
                _optional_float(row.get("target_quantity")),
                _optional_float(row.get("estimated_delta_quantity")),
                _optional_float(row.get("estimated_value_dkk")),
                str(row.get("priority") or "medium"),
                float(row.get("confidence") or 0.0),
                str(row.get("rationale") or ""),
                json.dumps(row.get("risk") or {}, ensure_ascii=False, sort_keys=True),
            )
        )
    if sentiment_rows:
        connection.executemany(
            """
            INSERT INTO swing_sentiment_snapshots (
                created_at, report_id, pulse_key, symbol, sentiment, confidence,
                macro_bias, rationale, catalysts_json, risk_notes_json, source_json
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            sentiment_rows,
        )
    if target_rows:
        connection.executemany(
            """
            INSERT INTO swing_position_targets (
                created_at, report_id, pulse_key, symbol, sentiment, action,
                current_weight_pct, target_weight_pct, current_quantity, target_quantity,
                estimated_delta_quantity, estimated_value_dkk, priority, confidence,
                rationale, risk_json
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            target_rows,
        )
    connection.commit()


def _optional_float(value: Any) -> float | None:
    if value is None:
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def datetime_now_iso() -> str:
    from datetime import UTC, datetime

    return datetime.now(UTC).isoformat(timespec="seconds")
